# Generated by Django 5.2.4 on 2026-09-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_joiner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joiner',
            options={'verbose_name': 'joiner'},
        ),
    ]
