# Generated by Django 5.2.4 on 2026-09-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_joiner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='chapter',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Internal information'), (2, 'Security awareness')], default=1),
        ),
    ]
