# Generated by Django 5.2.4 on 2026-09-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_material_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='locked',
            field=models.BooleanField(default=False, help_text='Joiners can only open this once every other active, unlocked material in the same chapter is completed.', verbose_name='locked until the rest of its chapter is completed'),
        ),
    ]
