# Generated by Django 5.2.4 on 2026-09-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_material_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('link', 'Link'), ('image', 'Image')], max_length=5),
        ),
    ]
