# Generated by Django 5.2.4 on 2026-09-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_material_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(blank=True, help_text='Image materials only: a short description of what the image shows (about 150 characters) for screen-reader users. Leave blank to use the title.', max_length=300, verbose_name='image description'),
        ),
    ]
