# Generated by Django 5.2.4 on 2026-09-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_material_description_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='url',
            field=models.URLField(blank=True, help_text='Link materials, or a video without an uploaded file (e.g. YouTube). An uploaded video file takes priority.'),
        ),
    ]
